name: Push To ocm-container

on:
  release:
    types: [published]

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout ocm-container project
      uses: actions/checkout@v2.3.4
      with:
        repository: openshift/ocm-container
#https://github.com/marketplace/actions/get-latest-release
    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@master
      with:
        find: "hello"
        replace: "world"
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3.8.2
      with:
        commit-message: "chore(osdctl): bump version to"
